package com.techreport.app

import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import java.text.SimpleDateFormat
import java.util.*

val systems=listOf("CCTV","Access Control","Burglar Alarm","Fire Alarm","Networking / Fiber")
val inspectionMap=mapOf(
 "CCTV" to listOf("Cameras","NVR","HDD","Recording","UPS/Battery","PoE/Network","Cabling"),
 "Access Control" to listOf("Access Control Machine/Controller","Access Control Reader","Magnetic Lock","Push Button","Emergency Release/Break Glass","Power Supply","UPS/Battery","Door Contact/Door Sensor"),
 "Burglar Alarm" to listOf("Alarm Panel","PIR Sensor","Door Magnetic Contact Sensor","Keypad/Control","Siren","Battery/Power Supply","Shock Sensor"),
 "Fire Alarm" to listOf("Fire Alarm Panel","Smoke Detector","Heat Detector","Manual Call Point","Sounder/Bell/Strobe","Battery/Power Supply"),
 "Networking / Fiber" to listOf("Network Switch","Router/Firewall","Access Point","Fiber Link/SFP","UTP/Fiber Cabling")
)

class MainActivity:ComponentActivity(){
 private lateinit var db:AppDb
 override fun onCreate(b:Bundle?){super.onCreate(b);db=AppDb(this);setContent{TechReportApp()}}
 @Composable fun TechReportApp(){var page by remember{mutableStateOf("home")};MaterialTheme(colorScheme=lightColorScheme(primary=androidx.compose.ui.graphics.Color(0xFF6A1B9A))){when(page){"home"->Home{page=it};"service"->ServiceScreen{page=it};"install"->InstallScreen{page=it};"sites"->SitesScreen{page=it};"profile"->ProfileScreen{page=it}}}}
 @Composable fun Shell(title:String,back:()->Unit,content:@Composable ColumnScope.()->Unit){Scaffold(topBar={TopAppBar(title={Text(title)},navigationIcon={TextButton(onClick=back){Text("‹")}})}){p->Column(Modifier.padding(p).padding(16.dp),content=content)}}
 @Composable fun Home(nav:(String)->Unit){Scaffold(topBar={TopAppBar(title={Text("TechReport")})}){p->Column(Modifier.fillMaxSize().padding(p).padding(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Field Technician Service Manager",style=MaterialTheme.typography.titleMedium);Button({nav("service")},Modifier.fillMaxWidth()){Text("1. Service / Troubleshooting Report")};Button({nav("install")},Modifier.fillMaxWidth()){Text("2. New Installation / Asset Report")};Button({nav("sites")},Modifier.fillMaxWidth()){Text("3. Existing Sites")};Button({nav("profile")},Modifier.fillMaxWidth()){Text("4. Technician Profile")}}}}
 @Composable fun ServiceScreen(nav:(String)->Unit){val sites=db.sites();var site by remember{mutableStateOf(sites.firstOrNull())};var system by remember{mutableStateOf(systems[0])};var visit by remember{mutableStateOf("Service")};var serviceNo by remember{mutableStateOf("1st")};var rec by remember{mutableStateOf("")};val statuses=remember(system){inspectionMap[system]!!.associateWith{mutableStateOf("Good")}};val remarks=remember(system){inspectionMap[system]!!.associateWith{mutableStateOf("")}};Shell("Service / Troubleshooting",{nav("home")}){Text("Site",style=MaterialTheme.typography.titleMedium);sites.forEach{s->RadioButton(selected=site?.id==s.id,onClick={site=s});Text(s.name)};Text("Visit Type");systemsForVisit(visit){visit=it};if(visit=="Service"){Text("Service No");serviceNoField(serviceNo){serviceNo=it}};Text("System");systemMenu(system){system=it};inspectionMap[system]!!.forEach{i->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(10.dp)){Text(i);Row{listOf("Good","Fair","Fault").forEach{RadioButton(statuses[i]!!.value==it,{statuses[i]!!.value=it});Text(it)}};OutField(remarks[i]!!.value,"Remarks"){remarks[i]!!.value=it}}};OutField(rec,"Recommendation"){rec=it};Button({site?.let{s->val r=ServiceReport(siteId=s.id,visitType=visit,serviceNo=serviceNo,system=system,recommendation=rec,date=today());val id=db.addService(r);Pdf.service(this@MainActivity,s,r,inspectionMap[system]!!.map{i->Inspection(i,statuses[i]!!.value,remarks[i]!!.value)});Toast.makeText(this@MainActivity,"Report saved + PDF created",Toast.LENGTH_LONG).show();nav("home")}},Modifier.fillMaxWidth()){Text("Save Report & Generate PDF")}}}
 @Composable fun InstallScreen(nav:(String)->Unit){val sites=db.sites();var site by remember{mutableStateOf(sites.firstOrNull())};var system by remember{mutableStateOf(systems[0])};var type by remember{mutableStateOf(inspectionMap[system]!!.first())};var brand by remember{mutableStateOf("")};var model by remember{mutableStateOf("")};var serial by remember{mutableStateOf("")};var ip by remember{mutableStateOf("")};var loc by remember{mutableStateOf("")};var qty by remember{mutableStateOf("1")};var date by remember{mutableStateOf(today())};var remarks by remember{mutableStateOf("")};var secret by remember{mutableStateOf("")};var assets by remember{mutableStateOf(listOf<Asset>())};Shell("Installation / Asset Register",{nav("home")}){sites.forEach{s->Row{RadioButton(site?.id==s.id,{site=s});Text(s.name)}};Text("System");systemMenu(system){system=it;type=inspectionMap[it]!!.first()};Text("Device Type");systemMenu(type){type=it};OutField(brand,"Brand"){brand=it};OutField(model,"Model"){model=it};OutField(serial,"Serial Number"){serial=it};OutField(ip,"IP Address (if applicable)"){ip=it};OutField(loc,"Location"){loc=it};OutField(qty,"Quantity"){qty=it};OutField(date,"Installation Date"){date=it};OutField(remarks,"Remarks"){remarks=it};OutField(secret,"Device/NVR/Camera Password (encrypted storage; hidden from PDF)"){secret=it};Button({site?.let{s->assets=assets+Asset(siteId=s.id,system=system,type=type,brand=brand,model=model,serial=serial,ip=ip,location=loc,qty=qty.toIntOrNull()?:1,installDate=date,remarks=remarks,secret=secret);brand="";model="";serial="";ip="";loc="";remarks="";secret=""}},Modifier.fillMaxWidth()){Text("Add Device")};Text("Devices added: ${assets.size}");Button({site?.let{s->assets.forEach{db.addAsset(it)};Pdf.installation(this@MainActivity,s,system,assets);Toast.makeText(this@MainActivity,"Installation saved + PDF created",Toast.LENGTH_LONG).show();nav("home")}},Modifier.fillMaxWidth()){Text("Save Asset Register & Generate PDF")}}}
 @Composable fun SitesScreen(nav:(String)->Unit){var show by remember{mutableStateOf(false)};var name by remember{mutableStateOf("")};var job by remember{mutableStateOf("")};var customer by remember{mutableStateOf("")};var person by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var address by remember{mutableStateOf("")};Shell("Existing Sites",{nav("home")}){Button({show=true}){Text("+ Add Site")};db.sites().forEach{s->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(12.dp)){Text(s.name,style=MaterialTheme.typography.titleMedium);Text("Job: ${s.job}");Text("Customer: ${s.customer}");Text(s.address)}}};if(show)AlertDialog(onDismissRequest={show=false},confirmButton={Button({db.addSite(Site(name=name,job=job,customer=customer,person=person,phone=phone,address=address));show=false;nav("sites")}){Text("Save")}},dismissButton={TextButton({show=false}){Text("Cancel")}},title={Text("New Site")},text={Column{OutField(name,"Site Name"){name=it};OutField(job,"Job Number"){job=it};OutField(customer,"Company / Customer"){customer=it};OutField(person,"Contact Person"){person=it};OutField(phone,"Contact Number"){phone=it};OutField(address,"Address"){address=it}}})}}
 @Composable fun ProfileScreen(nav:(String)->Unit){var company by remember{mutableStateOf("")};var name by remember{mutableStateOf("")};var email by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var epf by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};Shell("Technician Profile",{nav("home")}){OutField(company,"Company Name"){company=it};OutField(name,"Technician Name"){name=it};OutField(email,"Email"){email=it};OutField(phone,"Phone Number"){phone=it};OutField(epf,"EPF Number"){epf=it};OutField(pass,"Password"){pass=it};Button({db.saveTechnician(company,name,email,phone,epf,pass);Toast.makeText(this@MainActivity,"Profile saved",Toast.LENGTH_SHORT).show()}){Text("Save Profile")}}}
 @Composable fun OutField(v:String,label:String,on:(String)->Unit){OutlinedTextField(v,onValueChange=on,label={Text(label)},modifier=Modifier.fillMaxWidth().padding(vertical=4.dp),singleLine=true)}
 @Composable fun systemMenu(v:String,on:(String)->Unit){var open by remember{mutableStateOf(false)};Box{OutlinedButton({open=true},Modifier.fillMaxWidth()){Text(v)};DropdownMenu(open,{open=false}){(if(systems.contains(v))systems else inspectionMap.values.flatten().distinct()).forEach{x->DropdownMenuItem({Text(x)},{on(x);open=false})}}}}
 @Composable fun systemsForVisit(v:String,on:(String)->Unit){systemMenu(v,on)}
 @Composable fun serviceNoField(v:String,on:(String)->Unit){systemMenu(v,on)}
 fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(Date())
}
